# Generated by Django 3.1.6 on 2021-02-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olistbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_doc', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sport',
            name='num_doc',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='phone',
        ),
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
